using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeafX.Roy.Business
{
    public class TemplateWriter
    {
        public Font TitleFont { get; set; }

        public Font SubtitleFont { get; set; }

        public TemplateWriter()
        {
            TitleFont = Font.ParseFont("Broadway");
            SubtitleFont = Font.ParseFont("4Max");
        }

        public void PrintToFile(string filePath, string title, string subtitle)
        {
            var titleStrings = TitleFont.GetStringRows(title);
            var subTitleStrings = SubtitleFont.GetStringRows(subtitle);

            var titleLength = titleStrings[0].Length;
            var subTitleLength = subTitleStrings[0].Length;

            var maxWidth = Math.Max(titleLength, subTitleLength);



            if(titleLength != maxWidth)
            {
                foreach(var strBuilder in titleStrings)
                {
                    strBuilder.Insert(0, " ", (maxWidth - titleLength) / 2);
                }
            }
            else
            {
                foreach (var strBuilder in subTitleStrings)
                {
                    strBuilder.Insert(0, " ", (maxWidth - subTitleLength) / 2);
                }
            }

            using (var fileStream = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                using (var streamWriter = new StreamWriter(fileStream))
                {
                    foreach(var str in titleStrings)
                    {
                        streamWriter.WriteLine(str.ToString());
                    }

                    streamWriter.WriteLine();

                    foreach (var str in subTitleStrings)
                    {
                        streamWriter.WriteLine(str.ToString());
                    }

                    streamWriter.WriteLine(new String('-', maxWidth));

                    streamWriter.WriteLine();
                    streamWriter.WriteLine();
                    streamWriter.WriteLine();
                    streamWriter.WriteLine();
                    streamWriter.WriteLine();

                    var signString = $"-- Generated by DeafX.Roy {DateTime.Now.ToString("yyyy-MM-dd HH:mm")} ";
                    streamWriter.WriteLine(new String('-', maxWidth));
                    streamWriter.WriteLine(signString + new String('-', maxWidth - signString.Length));
                    streamWriter.WriteLine(new String('-', maxWidth));

                }
            }


        }


    }
}
